"""Dream Propose Phase — Pattern analysis and actionable proposal generation.

Weekly phase (runs separate from daily consolidation):
  1. Scan all memories in the vault
  2. Detect actionable patterns via LLM
  3. Generate proposals
  4. ≥77% confidence → auto-create Linear task
     <77% confidence → store as proposal memory, surface in morning report
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .store import DreamStore
from .taxonomy import MEMORY_TYPES, parse_frontmatter

logger = logging.getLogger(__name__)

# Manifest key for proposals
_PROPOSAL_KIND = "proposal"


# --------------------------------------------------------------------------
# Dataclasses
# --------------------------------------------------------------------------


@dataclass
class PatternFinding:
    """A single pattern detected in the vault."""
    pattern_type: str          # e.g. "theme_emergence", "gap_detection"
    summary: str                # Human-readable description of what was found
    evidence_memory_keys: List[str]  # ["user:slug1.md", "feedback:slug2.md"]
    confidence: float           # 0.0–1.0


@dataclass
class Proposal:
    """An actionable proposal generated by the Propose phase."""
    title: str
    body: str                   # Structured: What I Noticed / Evidence / Recommendation
    confidence: float           # 0.0–1.0
    pattern_type: str            # Which detector triggered this
    related_memory_keys: List[str]
    tags: List[str]


@dataclass
class ProposeResult:
    """Result of a full Propose phase run."""
    patterns_found: List[PatternFinding]
    proposals_generated: List[Proposal]
    proposals_stored: int
    errors: List[str]
    dry_run: bool = False


# --------------------------------------------------------------------------
# Manifest scanning helpers
# --------------------------------------------------------------------------


def _load_full_vault_memories(store: DreamStore) -> List[Dict[str, Any]]:
    """Load all memories from the manifest with their full content.

    Returns a list of dicts with keys: memory_type, filename, meta, body.
    Skips proposal-type entries (those are the output, not the input).
    """
    from .store import _load_manifest

    manifest = _load_manifest(store.dream_root)
    memories = []

    for entry in manifest:
        mem_type = entry.get("memory_type") or entry.get("type", "")
        # Skip proposals — they're the output, not input
        if mem_type == _PROPOSAL_KIND or mem_type not in MEMORY_TYPES:
            continue

        filename = entry.get("filename", "")
        if not filename:
            continue

        try:
            full = store.read_memory(mem_type, filename)
            memories.append({
                "memory_type": mem_type,
                "filename": filename,
                "slug": entry.get("slug", filename.rsplit(".md", 1)[0] if filename else ""),
                "meta": full.get("meta", {}),
                "body": full.get("body", ""),
                "created": entry.get("created", ""),
                "importance": entry.get("importance", 0.5),
                "relevance": entry.get("relevance", 0.5),
                "tags": entry.get("tags", []),
                "source": entry.get("source", ""),
            })
        except Exception as exc:
            logger.debug("Skipping unreadable memory %s/%s: %s", mem_type, filename, exc)
            continue

    return memories


def _summarize_memory(mem: Dict[str, Any]) -> str:
    """One-line summary of a memory for LLM context."""
    mem_type = mem["memory_type"]
    slug = mem["slug"]
    tags = ", ".join(mem.get("tags", [])[:5])
    importance = mem.get("importance", 0.5)
    created = mem.get("created", "")[:10]
    body_preview = mem["body"].replace("\n", " ")[:120].strip()
    return f"[{mem_type}] {slug} (importance={importance}, created={created}, tags=[{tags}]) — {body_preview}"


# --------------------------------------------------------------------------
# Pattern detection via LLM
# --------------------------------------------------------------------------


def _detect_patterns(memories: List[Dict[str, Any]], config: dict) -> List[PatternFinding]:
    """Send all memories to LLM to detect actionable patterns.

    Returns a list of PatternFinding objects.
    """
    if not memories:
        return []

    # Build concise context for the LLM
    memory_summaries = [_summarize_memory(m) for m in memories]
    context_block = "\n".join(memory_summaries)

    prompt = f"""You are analyzing a personal AI agent's (Garuda's) memory vault from the past week.
Your job is to detect actionable patterns — things worth proposing to the user as concrete next steps.

Memory vault summary ({len(memories)} memories):
{context_block}

---

Look for these 5 pattern types ONLY:

1. THEME_EMERGENCE: 3+ user/feedback memories sharing a tag within the same week — suggests a persistent concern or interest worth addressing structurally.

2. GAP_DETECTION: User has expressed a need/goal (user memory) but no corresponding project memory shows progress being made on it — possible stalled initiative.

3. RECURRING_BLOCKERS: 2+ feedback memories labeled negative about the same theme (e.g., "I keep having to re-explain X", "the same bug keeps happening") — systemic issue.

4. PREFERENCE_CLUSTERING: 3+ separate user memories about the same topic but with different specifics — should be consolidated into one coherent preference.

5. CROSS_TYPE_OPPORTUNITY: A reference memory (external resource — tool, company, person) + a user memory expressing a need that resource could address — propose the explicit connection.

---

Respond with a JSON array of detected patterns. Each object must have:
- "pattern_type": one of THEME_EMERGENCE, GAP_DETECTION, RECURRING_BLOCKERS, PREFERENCE_CLUSTERING, CROSS_TYPE_OPPORTUNITY
- "summary": 1-2 sentence description of what you found and why it matters
- "evidence_memory_keys": list of memory keys (format: "type/slug") that support this pattern
- "confidence": float 0.0-1.0, how confident you are this is a real actionable pattern (not noise)

Only include patterns with confidence >= 0.5.
Return an empty array if no actionable patterns are found.
Respond with ONLY the JSON array, no markdown formatting, no explanation."""

    raw = _call_llm(prompt, config)
    if not raw:
        return []

    try:
        # Strip any markdown fences
        raw = raw.strip()
        if raw.startswith("```"):
            raw = re.sub(r"^```(?:json)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            return []

        findings = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            pt = item.get("pattern_type", "")
            conf = float(item.get("confidence", 0.0))
            if conf < 0.5:
                continue
            findings.append(PatternFinding(
                pattern_type=pt,
                summary=str(item.get("summary", "")),
                evidence_memory_keys=[str(k) for k in item.get("evidence_memory_keys", [])],
                confidence=conf,
            ))
        return findings
    except json.JSONDecodeError as exc:
        logger.warning("Failed to parse pattern detection LLM output: %s", exc)
        return []


# --------------------------------------------------------------------------
# Proposal generation via LLM
# --------------------------------------------------------------------------


def _generate_proposals(
    findings: List[PatternFinding],
    memories: List[Dict[str, Any]],
    config: dict,
) -> List[Proposal]:
    """Given pattern findings, generate structured proposals."""
    if not findings:
        return []

    # Build a memory lookup
    memories_by_key: Dict[str, Dict[str, Any]] = {}
    for m in memories:
        key = f"{m['memory_type']}/{m['slug']}"
        memories_by_key[key] = m

    # Build evidence block for each finding
    findings_block = []
    for i, f in enumerate(findings, 1):
        evidence_lines = []
        for ek in f.evidence_memory_keys:
            if ek in memories_by_key:
                mem = memories_by_key[ek]
                evidence_lines.append(f"  - [{ek}]: {mem['body'][:200]}")
            else:
                evidence_lines.append(f"  - [{ek}]: (memory content unavailable)")
        findings_block.append(
            f"{i}. [{f.pattern_type}] confidence={f.confidence}\n"
            f"   Summary: {f.summary}\n"
            f"   Evidence:\n" + "\n".join(evidence_lines)
        )

    findings_text = "\n\n".join(findings_block)

    prompt = f"""You are Garuda, a senior product and AI architect working autonomously.
Based on the pattern analysis of your memory vault from the past week, generate 1-3 concrete, actionable proposals for the user (Dimas/Kedar).

## Detected Patterns

{findings_text}

---

For each pattern, generate a proposal with this exact structure:

## Proposal N: [Clear action-oriented title]

### What I Noticed
[2-3 sentences explaining what pattern you found and why it matters]

### Evidence
[List the specific memories that support this, with concrete quotes where possible]

### What I Recommend
[The specific next step — be concrete. Name the tool, the approach, the company, the action. Avoid vague suggestions like "consider" or "explore".]

### Why This Matters
[1-2 sentences on the expected outcome if this is acted on]

Format rules:
- Title must be a clear imperative or noun phrase, not vague ("Create a job-targeting framework" not "Maybe think about jobs")
- Recommendation must name specific things (company names, tool names, action names)
- Confidence = your confidence this proposal will genuinely help Dimas
- Tags must be 2-4 specific tags from: job-search, career, garuda, dream-plugin, preference, feedback, project, product, ai-ml, strategy

Respond with a JSON array of proposals:
[
  {{
    "title": "Proposal title",
    "body": "Full proposal body with ## What I Noticed / ## Evidence / ## What I Recommend / ## Why This Matters",
    "confidence": 0.82,
    "pattern_type": "GAP_DETECTION",
    "related_memory_keys": ["user/job-targeting-20260410", "feedback/outreach-stall-20260412"],
    "tags": ["job-search", "career", "strategy"],
    "auto_action": "linear" or "review"
  }}
]

auto_action rules: no longer applicable — all proposals are stored for review.

Return ONLY the JSON array, no markdown, no explanation."""

    raw = _call_llm(prompt, config)
    if not raw:
        return []

    try:
        raw = raw.strip()
        if raw.startswith("```"):
            raw = re.sub(r"^```(?:json)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            return []

        proposals = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            proposals.append(Proposal(
                title=str(item.get("title", "Untitled")),
                body=str(item.get("body", "")),
                confidence=float(item.get("confidence", 0.0)),
                pattern_type=str(item.get("pattern_type", "")),
                related_memory_keys=[str(k) for k in item.get("related_memory_keys", [])],
                tags=item.get("tags", [])[:5],
            ))
        return proposals
    except json.JSONDecodeError as exc:
        logger.warning("Failed to parse proposal generation LLM output: %s", exc)
        return []


# --------------------------------------------------------------------------
# LLM caller (mirrors consolidation.py pattern)
# --------------------------------------------------------------------------


def _call_llm(prompt: str, config: dict) -> str:
    """Call the configured LLM for inference."""
    api_key = os.environ.get("OPENROUTER_API_KEY") or os.environ.get("OPENAI_API_KEY")
    model = config.get("propose_model", "google/gemini-2.0-flash")
    base_url = config.get("propose_base_url", "https://openrouter.ai/api/v1")

    if not api_key:
        logger.warning("No API key available for Propose phase LLM call")
        return ""

    import urllib.request
    import urllib.error

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    body = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2048,
        "temperature": 0.3,  # Low temp for structured analysis
    }).encode("utf-8")

    req = urllib.request.Request(
        f"{base_url}/chat/completions",
        data=body,
        headers=headers,
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data["choices"][0]["message"]["content"]
    except (urllib.error.HTTPError, urllib.error.URLError, KeyError, IndexError, json.JSONDecodeError) as exc:
        logger.warning("LLM call failed: %s", exc)
        return ""


# --------------------------------------------------------------------------
# Main entry point
# --------------------------------------------------------------------------


def run_propose_phase(
    store: DreamStore,
    config: Optional[dict] = None,
    dry_run: bool = False,
) -> ProposeResult:
    """Run the weekly Propose phase.

    1. Scan all memories in the vault
    2. Send vault state to LLM for pattern detection
    3. Generate structured proposals
    4. ≥77% confidence → auto-create Linear task
       <77% confidence → store as proposal memory

    Parameters
    ----------
    store:
        The DreamStore instance.
    config:
        Optional config dict. Supports ``propose_model``, ``propose_base_url``.
    dry_run:
        If True, report what would happen without making changes or storing.

    Returns
    -------
    ProposeResult
    """
    config = config or {}
    result = ProposeResult(
        patterns_found=[],
        proposals_generated=[],
        proposals_stored=0,
        errors=[],
        dry_run=dry_run,
    )

    # Step 1: Load all vault memories
    logger.info("Propose phase: scanning vault memories...")
    memories = _load_full_vault_memories(store)
    logger.info("Propose phase: found %d memories", len(memories))

    if not memories:
        result.errors.append("No memories found in vault")
        return result

    # Step 2: Pattern detection via LLM
    logger.info("Propose phase: detecting patterns...")
    findings = _detect_patterns(memories, config)
    result.patterns_found = findings
    logger.info("Propose phase: found %d patterns", len(findings))

    if not findings:
        logger.info("Propose phase: no actionable patterns detected")
        return result

    # Step 3: Generate proposals
    logger.info("Propose phase: generating proposals...")
    proposals = _generate_proposals(findings, memories, config)
    result.proposals_generated = proposals
    logger.info("Propose phase: generated %d proposals", len(proposals))

    if not proposals:
        result.errors.append("LLM failed to generate proposals")
        return result

    # Step 4: Execute — store proposals
    for proposal in proposals:
        if dry_run:
            logger.info("[DRY RUN] Would create proposal: %s (confidence=%.0f%%)",
                        proposal.title, proposal.confidence * 100)
            result.proposals_stored += 1
            continue

        # Store the proposal memory
        try:
            store.add_proposal(
                title=proposal.title,
                body=proposal.body,
                confidence=proposal.confidence,
                tags=proposal.tags,
                related_memory_refs=proposal.related_memory_keys,
                source="propose-phase",
                importance=proposal.confidence,
                relevance=0.8,
            )
            result.proposals_stored += 1
        except Exception as exc:
            err = f"Failed to store proposal '{proposal.title}': {exc}"
            logger.error(err)
            result.errors.append(err)
            continue

    logger.info(
        "Propose phase complete: %d patterns, %d proposals, %d stored",
        len(result.patterns_found),
        len(result.proposals_generated),
        result.proposals_stored,
    )
    return result
